project:
  type: website

website:
  title: "Lauren Ilano"
  description: ""
  page-footer: 
    left: "Made with [Quarto](https://quarto.org/)"
    right: 
      - text: "Contact Me"
      - icon: envelope
        href: mailto:laurenilano@gmail.com
  navbar:
    right:
      - text: About Me
        href: about.qmd
      - text: Blog
        href: blog.qmd
      - text: Resources
        href: resources.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: 'Ilano 2022 CV.pdf'
      - icon: github
        href: https://github.com/laurenilano
      - icon: book
        href: https://www.goodreads.com/user/show/68223454-lauren-m-ilano
format:
  html:
    theme: flatly
    css: styles.css



