project:
  type: website

website:
  title: "Lauren Ilano's blog"
  description: "this blog has useful tips about R"
  page-footer: 
    left: "Made by with [Quarto](https://quarto.org/)"
    right: 
      - icon: envelope
        href: mailto:laurenilano@gmail.com
  navbar:
    right:
      - about.qmd
      - text: Blog
        href: blog.qmd
      - text: Resources
        href: resources.qmd
      - icon: github
        href: https://github.com/laurenilano
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: journal
    css: styles.css



