project:
  type: website

website:
  title: "Lauren Ilano's blog"
  description: "this blog has useful tips about R"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Resources
        href: resources.qmd
      - icon: github
        href: https://github.com/laurenilano
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



