---
title: 'SQL/R Workflow'
date: '2022-08-10'
categories: ['SQL']
description: 'How to set up an analysis workflow using sql and r'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# Intro

While you could embed all your SQL queries into your .R scripts, it can get a bit messy. Instead, a better approach is to write out your SQL queries in SQLite Studio (or whatever GUI you prefer) and pulling in only the resulting table in R. 

This has a few advantages. First, you are able to troubleshoot in the SQL Studio environment and make sure all the pesky variable names are correctly spelled 0:)

Secondly, it helps modularize your code so if you decide you need to change a filter because now you want to exclude all dual enrolled students, you dont have to scroll to line 863 of your R script but can just open the .sql file and make the change there. 

# Code Folder
- Code
  \- 01.Get_SQL.sql
  \- 02.Analysis.R
  
  
# Example Query 
set up the example
show basic query that is saved as 01.GetSQL.sql script

# How to set up R Script

## Remember to connect to SQLite Database
  - link to other post
  
## Ingest Query
```{r}

```

## Explore dataset
- head

