---
title: 'Creating a Sample SQLite DB to Play With'
date: '2022-08-04'
categories: ['SQL', 'set-up']
description: 'Here we set up SQLite Studio to view a sample database'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# SQL, Databases, and R

Prior to working in IR, I had tried my best to learn SQL through online tutorials, but it was always difficult to grasp how I would use SQL on a daily basis because I never learned anything beyond the syntax. I knew how to write a select statement, but I couldn't necessarily imagine how and where I would type these statements in the real world. 

# The bigger picture
This blog post is the beginning of a series of posts that will hopefully help folks see how to host and query a database locally (using SQLiteStudio) and eventually connect to the database from R using the odbc package. To show the basic steps to set up and connect to a db, we will be using a simple toy database, chinook, that is widely available. My hope in the future is to create a toy IR database that is more similar to the types of queries we would run as IR professionals (i.e., fake student enrollment data, course/section data, term data, etc.)

# What is SQLite

# Setting Up SQLite and SQLiteStudio

# Importing the Chinook Database

# Exploring the Database

